// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Fs1bokNE96VvZoLSKIhfa88lcm9-w8A',
    appId: '1:309040849360:android:e67558df37e022f4bc99d5',
    messagingSenderId: '309040849360',
    projectId: 'redting-d5504',
    storageBucket: 'redting-d5504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5o9UXSTCyCMeMNYblbawbOTe_6MYmx8',
    appId: '1:309040849360:ios:9ce023fc88ca3d7abc99d5',
    messagingSenderId: '309040849360',
    projectId: 'redting-d5504',
    storageBucket: 'redting-d5504.appspot.com',
    androidClientId: '309040849360-gdiqkfnqtqd1cc5r0jbjglmofhp1je3h.apps.googleusercontent.com',
    iosClientId: '309040849360-ajflptqec7341i58rg3np5755gsi6ksc.apps.googleusercontent.com',
    iosBundleId: 'com.redting.developers.redting',
  );
}
